{{- if .Values.ingress.enabled -}}
{{- $fullName := include "demoapp.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "demoapp.labels" . | indent 4 }}
  annotations:
{{- if .Values.nginx.enabled }}
    kubernetes.io/ingress.class: {{ .Values.nginx.controller.ingressClass | quote }}
{{- else }}
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
spec:
  rules:
  - http:
      paths:
      {{ range include "demoapp.services" . | splitList " " }}
      {{ if eq . "frontend" }}
        - path: /{{ $.Release.Name }}/
      {{ else }}
        - path: /{{ $.Release.Name }}/{{ . }}
      {{ end }}
          backend:
            serviceName: {{ . }}
            servicePort: http
      {{ end }}
      {{ if .Values.jaeger.enabled }}
        - path: /{{ .Release.Name }}/jaeger
          backend:
            serviceName: {{ .Release.Name }}-jaeger-query
            servicePort: http
      {{ end }}
{{- end -}}
