apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "demoapp.fullname" . }}
  labels:
{{ include "demoapp.labels" . | indent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
        name: {{ include "demoapp.fullname" . }}
        labels:
{{ include "demoapp.labels" . | indent 10 }}
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-phippy-job
        image: "byrnedo/alpine-curl:0.1.7"
        command: ["/bin/sh","-c"]
        args:
          - |
            for i in 1 3 $(seq 4 2 20);
            do curl https://www.cncf.io/wp-content/uploads/2018/12/phippy-goes-to-the-zoo-$(printf %02d $i)-1.png --output /tmp/phippy-goes-to-the-zoo-$(printf %02d $i)-1.png || true;
            done;
            for i in $(ls /tmp/*.png);
            do (echo -n '{ "base64": "'"$(base64 $i | tr -d "\n" )"'"}')|curl -H "Content-Type: application/json" -d @- http://metadata:8000/v0/images;
            done;
