// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// TimeStamp Time stamp for an event related to an object, for example when the object was created.
// swagger:model TimeStamp
type TimeStamp strfmt.DateTime

// Validate validates this time stamp
func (m TimeStamp) Validate(formats strfmt.Registry) error {
	return nil
}
