// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"kio/requestid"
)

// NewGetImageParams creates a new GetImageParams object
// with the default values initialized.
func NewGetImageParams() *GetImageParams {
	var ()
	return &GetImageParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetImageParamsWithTimeout creates a new GetImageParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetImageParamsWithTimeout(timeout time.Duration) *GetImageParams {
	var ()
	return &GetImageParams{

		timeout: timeout,
	}
}

// NewGetImageParamsWithContext creates a new GetImageParams object
// with the default values initialized, and the ability to set a context for a request
// If ctx contains a request ID, this is automatically added to the params struct
func NewGetImageParamsWithContext(ctx context.Context) *GetImageParams {
	var ()

	params := &GetImageParams{

		Context: ctx,
	}

	id := requestid.FromContext(ctx)
	params.SetXRequestID(&id)
	return params
}

// NewGetImageParamsWithHTTPClient creates a new GetImageParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetImageParamsWithHTTPClient(client *http.Client) *GetImageParams {
	var ()
	return &GetImageParams{
		HTTPClient: client,
	}
}

/*GetImageParams contains all the parameters to send to the API endpoint
for the get image operation typically these are written to a http.Request
*/
type GetImageParams struct {

	/*XRequestID*/
	XRequestID *string
	/*ItemID
	  Item uuid for a request

	*/
	ItemID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get image params
func (o *GetImageParams) WithTimeout(timeout time.Duration) *GetImageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get image params
func (o *GetImageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get image params
func (o *GetImageParams) WithContext(ctx context.Context) *GetImageParams {
	o.SetContext(ctx)
	id := requestid.FromContext(ctx)
	o.SetXRequestID(&id)
	return o
}

// SetContext adds the context to the get image params
func (o *GetImageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get image params
func (o *GetImageParams) WithHTTPClient(client *http.Client) *GetImageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get image params
func (o *GetImageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRequestID adds the xRequestID to the get image params
func (o *GetImageParams) WithXRequestID(xRequestID *string) *GetImageParams {
	o.SetXRequestID(xRequestID)
	return o
}

// SetXRequestID adds the xRequestId to the get image params
func (o *GetImageParams) SetXRequestID(xRequestID *string) {
	o.XRequestID = xRequestID
}

// WithItemID adds the itemID to the get image params
func (o *GetImageParams) WithItemID(itemID strfmt.UUID) *GetImageParams {
	o.SetItemID(itemID)
	return o
}

// SetItemID adds the itemId to the get image params
func (o *GetImageParams) SetItemID(itemID strfmt.UUID) {
	o.ItemID = itemID
}

// WriteToRequest writes these params to a swagger request
func (o *GetImageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XRequestID != nil {

		// header param X-Request-ID
		if err := r.SetHeaderParam("X-Request-ID", *o.XRequestID); err != nil {
			return err
		}

	}

	// path param itemId
	if err := r.SetPathParam("itemId", o.ItemID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
